name: ML Pipeline

on: [push]

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        
    - name: Test parameter count
      run: |
        python -m unittest tests.test_model.TestModel.test_parameter_count
        
    - name: Test single epoch accuracy
      run: |
        python -m unittest tests.test_model.TestModel.test_single_epoch_accuracy
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 90